In [1]:
import tensorflow as tf

In [2]:
텐서 = tf.constant(3)
print(텐서)

tf.Tensor(3, shape=(), dtype=int32)


In [11]:
텐서 = tf.constant([3,4,5])
텐서2 = tf.constant([6,7,8])

print(텐서 + 텐서2)
print(tf.add(텐서, 텐서2))
print(tf.subtract(텐서, 텐서2))
print(tf.multiply(텐서, 텐서2))
print(tf.divide(텐서, 텐서2))

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([18 28 40], shape=(3,), dtype=int32)
tf.Tensor([0.5        0.57142857 0.625     ], shape=(3,), dtype=float64)


In [9]:
텐서3 = tf.constant([[1,2], [3,4]])
# 행렬
# |1 2| 
# |3 4|

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [12]:
텐서4 = tf.constant([[5,6], [7,8]])
tf.matmul(텐서3, 텐서4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [19]:
텐서5 = tf.zeros(9)
print(텐서5)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(9,), dtype=float32)


In [18]:
텐서6 = tf.zeros([3,3])
print(텐서6)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [20]:
텐서7 = tf.zeros([2,2,3]) #3개의 0이 들어있는 리스트를 2개 생성 후 또 다시 2개 생성
print(텐서7)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


In [25]:
텐서8 = tf.constant([[1,2,3],[4,5,6]])

print(텐서.shape)
print(텐서8.shape) # 3개의 원소를 가진 리스트가 2개가 있다 (2, 3)

(3,)
(2, 3)


In [28]:
# tf.constant는 고정된 값
# tf.Variable() 고정되지 않은 값 ex)weight
w = tf.Variable(1.0) # 초기값이 1.0

print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [29]:
w.assign(2)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>


In [34]:
print(w.numpy())

2.0
